# Generated by Django 3.2.5 on 2021-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isfavorited',
            options={'verbose_name': 'Любимый', 'verbose_name_plural': 'Любимые '},
        ),
        migrations.AlterModelOptions(
            name='isinshoppingcart',
            options={'verbose_name': 'В корзине', 'verbose_name_plural': 'В корзине'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='recipes',
                to='api.Tag',
                verbose_name='Тeги рецепта'
            ),
        ),
    ]
